// Code generated by MockGen. DO NOT EDIT.
// Source: buffered_writer.go

// Package lbwriter is a generated GoMock package.
package lenbytewriter

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLBWriter is a mock of LBWriter interface.
type MockLBWriter struct {
	ctrl     *gomock.Controller
	recorder *MockLBWriterMockRecorder
}

// MockLBWriterMockRecorder is the mock recorder for MockLBWriter.
type MockLBWriterMockRecorder struct {
	mock *MockLBWriter
}

// NewMockLBWriter creates a new mock instance.
func NewMockLBWriter(ctrl *gomock.Controller) *MockLBWriter {
	mock := &MockLBWriter{ctrl: ctrl}
	mock.recorder = &MockLBWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLBWriter) EXPECT() *MockLBWriterMockRecorder {
	return m.recorder
}

// WriteLengthWithData mocks base method.
func (m *MockLBWriter) WriteLengthWithData(data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", data)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteLengthWithData indicates an expected call of WriteLengthWithData.
func (mr *MockLBWriterMockRecorder) WriteLengthWithData(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockLBWriter)(nil).WriteLengthWithData), data)
}

// MockFlusher is a mock of Flusher interface.
type MockFlusher struct {
	ctrl     *gomock.Controller
	recorder *MockFlusherMockRecorder
}

// MockFlusherMockRecorder is the mock recorder for MockFlusher.
type MockFlusherMockRecorder struct {
	mock *MockFlusher
}

// NewMockFlusher creates a new mock instance.
func NewMockFlusher(ctrl *gomock.Controller) *MockFlusher {
	mock := &MockFlusher{ctrl: ctrl}
	mock.recorder = &MockFlusherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlusher) EXPECT() *MockFlusherMockRecorder {
	return m.recorder
}

// Flush mocks base method.
func (m *MockFlusher) Flush() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush")
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockFlusherMockRecorder) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockFlusher)(nil).Flush))
}
